image: node:14

pipelines:
  # default:
  #   - step:
  #       name: Run Test
  #       caches:
  #         - node
  #       script:
  #         - yarn install
  #         - echo This is where we run the test
  branches:
    develop:
      - step:
          name: Build
          caches:
            - node
          script:
            - yarn install
            - cp src/environments/environment.prod.ts src/environments/environment.ts
            - yarn run build
          artifacts:
            - dist/primalaeroibe/**
      - step:
          deployment: Development
          name: Deploy
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
                AWS_DEFAULT_REGION: $REGION
                S3_BUCKET: $BUCKET_NAME
                LOCAL_PATH: dist/primalaeroibe
                ACL: public-read

    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - yarn install
            - yarn run build --prod
            - apt-get update
            - apt-get install -y zip
            - cd dist/primalaeroibe && zip -r ../../application.zip .
          artifacts:
            # - dist/**
            - application.zip
      - step:
          deployment: Production
          name: Deploy
          script:
            - echo deploying application to production environment
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                ENVIRONMENT_NAME: $ENVIRONMENT_NAME
                ZIP_FILE: application.zip
                S3_BUCKET: $S3_BUCKET